#[programs.localnet]
#rs_staking_program = "AjVuYjwgipD3fsiDQfgqgJFA2TJa4mQNRapUxkQuzPhj"

[programs.devnet]
rs_staking_program = "AjVuYjwgipD3fsiDQfgqgJFA2TJa4mQNRapUxkQuzPhj"

#[programs.mainnet]
#rs_staking_program = "7GgQ6MgkgkT9QvFY6qZgnx41ZBWDdcv3ibeH5cJuybT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
